### ISSUE TITLE
Where is Azure translation?

### ISSUE THREAD

**Issue by kamoljan** [mjuenema/Terraform-Up-and-Running-Code-Samples-Translated#1]

**Comment by mjuenema** [comment]
There simple isn't one at the moment. It's something I'd like to add sometime in the future but as of today I have never actually used Azure. I am quietly hoping that someone will add examples for Azure, and possible other providers and create a Pull Request. Is that something you'd like to do?

**Comment by kamoljan** [comment]
@mjuenema let me see if I can find some time.
